services:
  backend:
    container_name: backend   
    image: 'projectback'
    ports:
      - 30100:50100
    env_file:
      - ../../Back/.env 
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096
    volumes:
      - ../../Back/src:/app/src
      - ../../Back/package.json:/app/package.json
    command: yarn nodemon
    networks:
      - app-net 
    depends_on: # ให้ Backend รอ MongoDB ก่อนสตาร์ท
      - mongo 

  frontend:
    container_name: frontend
    build: '.'
    ports:
      - 30101:5173
    depends_on:
      - backend   # รอ backend ก่อน
    networks:
      - app-net

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - 27017:27017
    volumes: # เพิ่ม Volume เพื่อเก็บข้อมูล MongoDB
      - mongo_data:/data/db
    networks:
      - app-net
volumes:
  mongo_data: # เก็บข้อมูล MongoDB ถาวร

networks:
  app-net:
    driver: bridge